#!/usr/bin/ruby

#### Configuration
REPO = "zhaobot/citra"
UPSTREAM = "citra-emu/citra"
REPO_PATH = "/home/runner/citra"
TRANSLATIONS_PATH = "#{REPO_PATH}/dist/languages"
AUTHOR = "The Citra Community <noreply-fake@community.citra-emu.org>"
BODY = "This PR is generated by [zhaowenlan1779/txbot](https://github.com/zhaowenlan1779/txbot)."
##########################################################

require 'txbot.rb'
