#!/usr/bin/ruby

#### Configuration
REPO = "zhaobot/yuzu"
UPSTREAM = "yuzu-emu/yuzu"
REPO_PATH = "/home/runner/yuzu"
TRANSLATIONS_PATH = "#{REPO_PATH}/dist/languages"
AUTHOR = "The yuzu Community <noreply-fake@community.yuzu-emu.org>"
BODY = "This PR is generated by [zhaowenlan1779/txbot](https://github.com/zhaowenlan1779/txbot)."
##########################################################

require 'txbot'
