name: citra-txbot

on:
  schedule:
    - cron: '30 1 1 2,4,6,8,10,12 *'
  workflow_dispatch: ~

jobs:
  tx-update:
    runs-on: ubuntu-latest
    container: yuzuemu/build-environments:linux-transifex
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up dependencies
        run: ./deps.sh
      - name: Pull and PR Translations
        run: ./txbot-citra.rb execute
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TX_TOKEN: ${{ secrets.TRANSIFEX_API_TOKEN }}
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          time_elapsed: 30
