name: citra-txbot

on:
  schedule:
    - cron: '30 1 1 2,4,6,8,10,12 *'
  workflow_dispatch: ~

jobs:
  tx-update:
    runs-on: ubuntu-latest
    container: citraemu/build-environments:linux-transifex
    steps:
      - uses: actions/checkout@v2
      - name: Set up Transifex client
        run: ./deps.sh
        env:
          TRANSIFEX_API_TOKEN: ${{ secrets.TRANSIFEX_API_TOKEN }}
      - name: Pull and PR Translations
        run: ./txbot-citra.rb
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
