name: yuzu-txbot

on:
  schedule:
    - cron: '30 1 1 * *'
  workflow_dispatch: ~

jobs:
  tx-update:
    runs-on: ubuntu-latest
    container: yuzuemu/build-environments:linux-transifex
    steps:
      - uses: actions/checkout@v3
      - name: "Add GitHub to the SSH known hosts file"
        run: |
          apt-get install -y jq
          mkdir -p -m 0700 /home/runner/.ssh
          curl --silent https://api.github.com/meta  | jq --raw-output '"github.com "+.ssh_keys[]' >> /home/runner/.ssh/known_hosts
          chmod 600 /home/runner/.ssh/known_hosts
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up dependencies
        run: ./deps.sh
      - name: Pull and PR Translations
        run: ./txbot-yuzu.rb execute
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          TX_TOKEN: ${{ secrets.TRANSIFEX_API_TOKEN }}
      # TODO: Why exactly is this necessary?
      - name: (HACK) Manually set safe
        run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          time_elapsed: 27
